name: Plan

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write       # OIDC authentication
  contents: read        # Read repository
  pull-requests: write  # Comment on PRs

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  TF_VAR_ecr_uri: ${{ vars.ECR_URI }}

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22.x

      - name: Build Services
        run: npm run build
        working-directory: ./services

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::786401692952:role/GitHubActionsTerraform
          aws-region: us-east-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.3
      
      - name: Init Terraform
        run: terraform init -no-color
        working-directory: ./terraform/deploy

      - name: Validate Terraform
        run: terraform validate -no-color
        working-directory: ./terraform/deploy
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color > tfplan.txt
        working-directory: ./terraform/deploy
        continue-on-error: true

      - name: Fail on Failed Plan
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Comment Plan on PR
        uses: mshick/add-pr-comment@v3
        with:
          message-path: ./terraform/deploy/tfplan.txt
          message-id: terraform-plan

  publish_plan:
    name: Publish Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Build Services
        run: npm run build
        working-directory: ./services

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::786401692952:role/GitHubActionsPagePublishing
          aws-region: us-east-1

      - name: Identify Logs To Be Published
        run: node services/packages/detect-changes/ ./site/src/content/logs publish-plan.json

      - name: Comment Plan on PR
        uses: mshick/add-pr-comment@v3
        with:
          message-path: publish-plan.json
          message-id: publish-plan