name: Terraform Apply

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write       # OIDC authentication
  contents: read        # Read repository

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_KEY }}

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::786401692952:role/GitHubActionsTerraform
          aws-region: us-east-1
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
      
      - name: Init Terraform
        run: terraform init -no-color
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform